### ISSUE TITLE
Speed Output Units - CalculateRoadPerformance package

### ISSUE THREAD

**Issue by shichenfan** [VisionEval/VisionEval-Dev#122] opened 2020-09-22 19:55 UTC
Speed output from VE-Installer-Windows-R4.0.2, units were descried as miles per hour.
FwyNoneCongSpeed, FwyModCongSpeed, FwyHvyCongSpeed, ...

For example, Output / Marea / FwyNoneCongSpeed.Rda is 'Average freeway speed (miles per hour) when there is no congestion'.
This value of the default test scenario is 1439.999, which seems too high for speed in MPH.

**Comment by jrawbits** [comment] 2020-09-23 12:27
I investigated this issue, and you're right: the speed is too high for "MPH". In fact, according to the attributes sent back from VisionEval the units for these quantities are "MI/DAY" (which is weird; decades ago when I was in engineering school, someone did a funny presentation where they reported speed in "furlongs per fortnight").  So the MI/HOUR version would be 1439.99/24 which yields almost exactly 60 MI/HOUR, which is quite reasonable for uncongested freeway speed.

So we really have two issues:
1) How to detect the (possibly weird) units that are saved within VisionEval.
2) How to get the results in units that make more sense.

1) Detecting the units can be done with the new end-user API after you have run the model, like this:

    rspm <- openModel("MyRSPM")
    # rspm$run()  if you haven't already
    rspm$list(pattern="CongSpeed",index=TRUE)[,c("Name","Units")]
    218  ArtExtCongSpeed MI/DAY
    216  ArtHvyCongSpeed MI/DAY
    215  ArtModCongSpeed MI/DAY
    214 ArtNoneCongSpeed MI/DAY
    ......

2) You can do the unit conversion after that manually, or the new set of query scripts (based on the framework function summarizeDatasets) can do a unit conversion for you (see tools/queries/Measures_Demo.R for a brief exaple).  Alternatively (I haven't tried this, but it should work), you could alter the "defs/units.csv" and change "time" from "DAY" to "HR" and then re-run the model. Some of the other quantities may end up weird as a result, however.

**Comment by jrawbits** [comment] 2020-09-23 12:34
I'm leaving this as an issue, since we'll want the extract and query functions to make it very easy to report model results in units of the user's choosing. VIsionEval has a complete set of unit conversions built in already, but we need to make the units intuitive and the conversion mechanism easy (including setting up useful units by default).

**Comment by arashasadabadi** [comment] 2020-11-04 06:00
@jrawbits While working on adding the Travel Time reliability to VETravelPerformance with Gayathri, we noticed this same problem with speed units. The interesting thing is when we use the speed by extracting the speed values through the "Get" specification in travel time reliability function , it gets the correct MI/Hour values, but the outputs in data store are the MI/DAY values. I'm still not sure why this happens but I suspect something is going on with setting the speed units in data store.

**Comment by jrawbits** [comment] 2020-11-04 12:55
@arashasadabadi That's expected behavior. The units in the datastore are always constructed from the units specified in units.csv. The units used inside a module are always whatever the unit specification is in the "Get" (and "Set") function. Conversions are done by the framework whenever data is is moved into or out of the Datastore.

The idea is that you can just ignore the units of the Datastore and just say what you want to work with in the module (using "Get" and "Set"). As long as the units are the right kind (e.g. speed as a ratio of distance to time, or some known kind of area) the conversions are automatically performed when the module loads or saves data.

No conversion is done on input files: whatever the "Inp" specification says is what has to be in the file.

By the way, what I'm adding to the export is the ability identify units for export and have them be converted the same way each module does it. I'm also going to add default unit conversions for some common fields (so we can automatically get miles/hour instead of miles/day when we extract).

**Comment by jrawbits** [comment] 2022-01-11 20:51
Closing this for now - there are other unit conversion issues that will remain open that should address the ongoing concerns.

**Closed by jrawbits** 2022-01-11 20:51 UTC
